---
deployment:
      tasks:
        - export DEPLOYPATH=/home/<jdcorp>/public_html 
        - /bin cp * $DEPLOYPATH                           
        - /bin cp /<sub_folder>/* $DEPLOYPATH            
        - /bin/cp -r * $DEPLOYPATH                        
        
        